Merge upstream branch (#6)
* Check LOGGING env-var for "true" (#78)

LOGGING env var should be exlicitly set to "true", in order to log
requests.

Currently it just needs to be truethy, which doesn't correspond with the
the current default value in the example .env.local file (where it's
"false").
Explicit "true" is also how other env-vars are checked, eg
https://github.com/microsoft/code-push-server/blob/08e97d751620ad7867bb0c9b94633e94f2c01c68/api/script/default-server.ts#L110

* Bump parse-duration from 1.1.0 to 2.1.3 in /cli (#95)

Bumps [parse-duration](https://github.com/jkroso/parse-duration) from
1.1.0 to 2.1.3.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/jkroso/parse-duration/releases">parse-duration's
releases</a>.</em></p>
<blockquote>
<h2>v2.1.3</h2>
<h2>What's Changed</h2>
<ul>
<li>Better performance / memory <a
href="https://redirect.github.com/jkroso/parse-duration/issues/61">#61</a></li>
<li>Safer RE <a
href="https://redirect.github.com/jkroso/parse-duration/issues/61">#61</a></li>
<li>Customizable placeholders</li>
<li>Type declaraion for rewriting units <a
href="https://redirect.github.com/jkroso/parse-duration/issues/62">#62</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/jkroso/parse-duration/compare/v2.1.2...v2.1.3">https://github.com/jkroso/parse-duration/compare/v2.1.2...v2.1.3</a></p>
<h2>v2.1.2</h2>
<h2>What's Changed</h2>
<ul>
<li>Fixed type definitions</li>
<li>Added abbrs <code>mo</code>, <code>mth</code>,
<code>microsec</code>, <code>nanosec</code></li>
<li>Removed <code>b</code> abbr</li>
<li>Removed <code>μ</code> as greek mu in favor of
<code>&amp;micro;</code> left in default set</li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/jkroso/parse-duration/compare/v2.1.1...v2.1.2">https://github.com/jkroso/parse-duration/compare/v2.1.1...v2.1.2</a></p>
<h2>v2.0.0</h2>
<ul>
<li>Introduces locales</li>
<li>Moves units into <code>parse.unit</code> object <a
href="https://redirect.github.com/jkroso/parse-duration/issues/56">#56</a></li>
<li>Abandons CJS format in favour of ESM</li>
<li>Adds locale-dependent group/decimal separator <a
href="https://redirect.github.com/jkroso/parse-duration/issues/35">#35</a></li>
</ul>
<h2>v1.1.2</h2>
<h2>What's Changed</h2>
<ul>
<li>style: improve typings by <a
href="https://github.com/nordluf"><code>@​nordluf</code></a> in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/22">jkroso/parse-duration#22</a></li>
<li>feat: enable default import syntax in typescript by <a
href="https://github.com/alonesuperman"><code>@​alonesuperman</code></a>
in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/24">jkroso/parse-duration#24</a></li>
<li>Make available unit types section a heading by <a
href="https://github.com/SparshithNR"><code>@​SparshithNR</code></a> in
<a
href="https://redirect.github.com/jkroso/parse-duration/pull/31">jkroso/parse-duration#31</a></li>
<li>Add typings for translations by <a
href="https://github.com/piotr-musialek-skyrise"><code>@​piotr-musialek-skyrise</code></a>
in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/38">jkroso/parse-duration#38</a></li>
<li>feat(types): export units type by <a
href="https://github.com/sawa-ko"><code>@​sawa-ko</code></a> in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/39">jkroso/parse-duration#39</a></li>
<li>Fix typings resolution when using TypeScript 4.7+ with ESM by <a
href="https://github.com/Nitive"><code>@​Nitive</code></a> in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/42">jkroso/parse-duration#42</a></li>
<li>Fix ESM types by <a
href="https://github.com/remcohaszing"><code>@​remcohaszing</code></a>
in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/43">jkroso/parse-duration#43</a></li>
<li>fix return type by <a
href="https://github.com/trim21"><code>@​trim21</code></a> in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/50">jkroso/parse-duration#50</a></li>
<li>Fix the type definitions for CJS by <a
href="https://github.com/remcohaszing"><code>@​remcohaszing</code></a>
in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/48">jkroso/parse-duration#48</a></li>
<li>Fix ESM types by <a
href="https://github.com/remcohaszing"><code>@​remcohaszing</code></a>
in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/47">jkroso/parse-duration#47</a></li>
<li>Fix types - use <code>null</code> instead of <code>undefined</code>
by <a
href="https://github.com/Mykhailo-Sichkaruk"><code>@​Mykhailo-Sichkaruk</code></a>
in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/53">jkroso/parse-duration#53</a></li>
<li>Add next unit support by <a
href="https://github.com/dy"><code>@​dy</code></a> in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/55">jkroso/parse-duration#55</a></li>
<li>Prevent using prototype properties as units by <a
href="https://github.com/goto-bus-stop"><code>@​goto-bus-stop</code></a>
in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/56">jkroso/parse-duration#56</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a href="https://github.com/nordluf"><code>@​nordluf</code></a> made
their first contribution in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/22">jkroso/parse-duration#22</a></li>
<li><a
href="https://github.com/alonesuperman"><code>@​alonesuperman</code></a>
made their first contribution in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/24">jkroso/parse-duration#24</a></li>
<li><a
href="https://github.com/SparshithNR"><code>@​SparshithNR</code></a>
made their first contribution in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/31">jkroso/parse-duration#31</a></li>
<li><a
href="https://github.com/piotr-musialek-skyrise"><code>@​piotr-musialek-skyrise</code></a>
made their first contribution in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/38">jkroso/parse-duration#38</a></li>
<li><a href="https://github.com/sawa-ko"><code>@​sawa-ko</code></a> made
their first contribution in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/39">jkroso/parse-duration#39</a></li>
<li><a href="https://github.com/Nitive"><code>@​Nitive</code></a> made
their first contribution in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/42">jkroso/parse-duration#42</a></li>
<li><a
href="https://github.com/remcohaszing"><code>@​remcohaszing</code></a>
made their first contribution in <a
href="https://redirect.github.com/jkroso/parse-duration/pull/43">jkroso/parse-duration#43</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/jkroso/parse-duration/commit/92bb91f111a57604c2b8c72373f605c1cdf1f895"><code>92bb91f</code></a>
2.1.3</li>
<li><a
href="https://github.com/jkroso/parse-duration/commit/9ccd9177bdd769b4d09a2931f908c029284b6500"><code>9ccd917</code></a>
Update Readme.md</li>
<li><a
href="https://github.com/jkroso/parse-duration/commit/0a2b7bf4ebeee28aa2fbb1b2ca0c366046c2395c"><code>0a2b7bf</code></a>
Update Readme.md</li>
<li><a
href="https://github.com/jkroso/parse-duration/commit/5aa4b90153467a25f93ec5274f77d9b18da3f049"><code>5aa4b90</code></a>
Update Readme.md</li>
<li><a
href="https://github.com/jkroso/parse-duration/commit/b58dd2cc6f2acf82baf6a93b7fde299885db876b"><code>b58dd2c</code></a>
Merge branch 'master' of <a
href="https://github.com/jkroso/parse-duration">https://github.com/jkroso/parse-duration</a></li>
<li><a
href="https://github.com/jkroso/parse-duration/commit/1d61c7250ee5bb4038a4e67144f88a78a5f8a4f9"><code>1d61c72</code></a>
Update Readme.md</li>
<li><a
href="https://github.com/jkroso/parse-duration/commit/9e88421bfd41806fa4b473bfb28a9ee9dafc27d7"><code>9e88421</code></a>
Merge pull request <a
href="https://redirect.github.com/jkroso/parse-duration/issues/61">#61</a>
from jkroso/fix-regex</li>
<li><a
href="https://github.com/jkroso/parse-duration/commit/2a340b5bcb727fe34ceb0bcbd7e01b1c65bde484"><code>2a340b5</code></a>
Make rewritable type</li>
<li><a
href="https://github.com/jkroso/parse-duration/commit/1d8086e599cc3c0c024e492bf595bd00bb4fadf3"><code>1d8086e</code></a>
Minot perf optimization attempt</li>
<li><a
href="https://github.com/jkroso/parse-duration/commit/04fc1b3dfb2a2d12f5c36f1c17ebe4adfe371c08"><code>04fc1b3</code></a>
Use dynamic cleanup regex</li>
<li>Additional commits viewable in <a
href="https://github.com/jkroso/parse-duration/compare/v1.1.0...v2.1.3">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=parse-duration&package-manager=npm_and_yarn&previous-version=1.1.0&new-version=2.1.3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)
You can disable automated security fix PRs for this repo from the
[Security Alerts
page](https://github.com/microsoft/code-push-server/network/alerts).

</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Add upper bound for parse-duration package version (#97)

NPM package
[parse-duration](https://www.npmjs.com/package/parse-duration) version
was bumped from `1.1.0` to `2.1.3` In PR #95 for CodePush CLI. This
caused the build to fail with the following error:

```shell
% npm run build

> code-push-cli@0.0.1 build
> tsc

script/command-parser.ts:1321:21 - error TS2349: This expression is not callable.
  Type 'typeof import("/private/tmp/ms-code-push-server/cli/node_modules/parse-duration/index")' has no call signatures.

1321   return Math.floor(parseDuration(durationString));
                         ~~~~~~~~~~~~~


Found 1 error in script/command-parser.ts:1321
```

As current code-base is not compatible with `parse-duration` versions
`2.0.0+`, restrict `parse-duration` to use version `1.x.y`.

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: Mikkel Gravgaard <mikkel@klokke.dk>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Priit Lätt <lattpriit@gmail.com>